Repository CA-G12/games-mohammd-fadi, pull requests merged in 2022-08, with the labels that each got.

#2 Complete file structure
  .eslintrc.json
  .gitignore
  package-lock.json
  package.json
  public/home/index.js
  public/home/styles.css
  public/index.html
  public/pages/error/404.html
  public/pages/error/500.html
  public/pages/error/index.js
  public/pages/error/styles.css
  public/pages/game/index.html
  public/pages/game/index.js
  public/pages/game/style.css
  src/app.js
  src/controllers/getHome.js
  src/controllers/index.js
  src/index.js
  src/routes.js
  tests/test.tests.js
Labels: done

#5 Add port using app.set and edit the start script
  package.json
  src/app.js
  src/index.js
Labels: await-review

#6 serve public static files into the server
  public/index.html
  src/app.js
Labels: await-review

#9 I added a tag img for testing api images
  public/index.html
Labels: await-review

#16 create simple html templete and some css style
  public/home/styles.css
  public/index.html
Labels: approved

#17 14 search autocomplete
  package.json
  public/home/index.js
  public/index.html
  src/controllers/index.js
  src/controllers/search.js
  src/routes.js
Labels: await-review

#20 create getGamesFromCategory controller and a router to handle the request from client side
  public/home/index.js
  src/controllers/getGamesFromCategory.js
  src/controllers/getHome.js
  src/controllers/index.js
  src/routes.js
Labels: await-review

#22 create requestGamesCategory to request data from the server and handle it
  public/home/index.js
Labels: await-review

#24 add some styles and create a section for lastest release game
  public/home/index.js
  public/home/styles.css
  public/index.html
Labels: await-review

#26 render game page for games when searching
  public/home/index.js
  public/index.html
  src/controllers/game.js
  src/controllers/getHome.js
  src/controllers/index.js
  src/routes.js
Labels: await-review

#27 create a controller and router for lastest releases games section
  src/controllers/getGamesFromCategory.js
  src/controllers/getLatestReleaseGames.js
  src/controllers/index.js
  src/routes.js
Labels: await-review

#29 create a render method
  package-lock.json
  public/home/index.js
Labels: await-review
